import "./globals.css";
import type { Metadata } from "next";
import SiteHeader from "@/components/ui/site-header";
import {
  titleFont,
  generalFont,
  sansFont,
  polyFont,
} from "../misc/fonts/fonts";

export const metadata: Metadata = {
  title: "Stereotype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${titleFont.variable} ${generalFont.variable} ${sansFont.variable} ${polyFont.variable} overflow-x-hidden`}
      >
        <SiteHeader />
        <aside className="fixed w-full h-screen" id="sidebar-portal-root"></aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
