import "./globals.css";
import type { Metadata } from "next";
import SiteHeader from "@/components/ui/site-header";
import {
  titleFont,
  generalFont,
  sansFont,
  polyFont,
} from "../misc/fonts/fonts";
import SiteFooter from "@/components/ui/site-footer";

export const metadata: Metadata = {
  title: "Stereotype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { story: string };
}) {
  return (
    <html lang="en">
      <body
        className={`${titleFont.variable} ${generalFont.variable} ${sansFont.variable} ${polyFont.variable}`}
      >
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
